- name: Base configure
  hosts: node:monitoring
  become: true
  roles:
    - users
    - docker
    - users_docker
    - hosts_monitoring

- name: Configure centralised monitoring server
  hosts: monitoring
  become: true
  roles:
    - server_monitoring

