user_groups:
  - name: developers
    gid: 1003
    docker_access: true
  - name: admins
    gid: 1002
    docker_access: true
    full_sudo: true

users:
  - name: developer1
    group: developers
    ssh_public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDoV8un31UtOT2zOEmNsgWAI8xWvXyjfBhEcwO1hjuGJG9HNiC7a8ncBw0QNAwIcEAbQU3t4hyOTDqIMYS7k1slU6qbBm4+/5Ab38OSCPaF/N8VvTrjkZhSw9VVXpUGQqgT8sMKdVsWKDbwmcmhOl6H4DQIfMbfsdiKYzUl5di6okdyUQ4VUvsvKjQSbroOAT4HCNHaOqGWkKy8gBXf3tKBsEVhGkaCndWu205rkcSbIHRVzhk+U6e/GnI29116tsoNg4/T0lVyfBj4sAONHUp9EJAEir/dpqMkZLV1vH+PWt7CZ0B+WU4lcUZ27JbfnrBiEN9IXf6dvoz1mzpkS6dqVZ+NTwIMUMawXOPAYRrSaNsLWu+Ksh6iuWvYn+qi3/ilS3x8aTyvvFO8iYf9Y/T7WYWp+yyekYuYG8GCqgNHB9H6pCIyWEqrcLV4/oWvgAHqlwdsKqJW+VI2TI62/7a+nSRuarWsz44W/kr/Y+ywZUtEz4Qm4p9wJXaXHEd4oJE= goldenjaden@DESKTOP-7O7A6SV"

  - name: admin1
    group: admins
    ssh_public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDoV8un31UtOT2zOEmNsgWAI8xWvXyjfBhEcwO1hjuGJG9HNiC7a8ncBw0QNAwIcEAbQU3t4hyOTDqIMYS7k1slU6qbBm4+/5Ab38OSCPaF/N8VvTrjkZhSw9VVXpUGQqgT8sMKdVsWKDbwmcmhOl6H4DQIfMbfsdiKYzUl5di6okdyUQ4VUvsvKjQSbroOAT4HCNHaOqGWkKy8gBXf3tKBsEVhGkaCndWu205rkcSbIHRVzhk+U6e/GnI29116tsoNg4/T0lVyfBj4sAONHUp9EJAEir/dpqMkZLV1vH+PWt7CZ0B+WU4lcUZ27JbfnrBiEN9IXf6dvoz1mzpkS6dqVZ+NTwIMUMawXOPAYRrSaNsLWu+Ksh6iuWvYn+qi3/ilS3x8aTyvvFO8iYf9Y/T7WYWp+yyekYuYG8GCqgNHB9H6pCIyWEqrcLV4/oWvgAHqlwdsKqJW+VI2TI62/7a+nSRuarWsz44W/kr/Y+ywZUtEz4Qm4p9wJXaXHEd4oJE= goldenjaden@DESKTOP-7O7A6SV"

nexus:
  proxy: http://192.168.0.123:5000
