- name: Install base packages
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    update_cache: true

- name: Add docker repo key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/{{ ansible_facts.distribution | lower }}/gpg
    state: present

- name: Add docker repo
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_facts.distribution | lower }} {{ ansible_facts.distribution_release }} stable"
    state: present
    filename: docker

- name: Install Docker Engine and compose
  ansible.builtin.apt:
    name:
      - "docker-ce={{ versions.docker_ce }}"
      - "docker-ce-cli={{ versions.docker_ce_cli }}"
      - "containerd.io={{ versions.containerd }}"
      - "docker-compose-plugin={{ versions.docker_compose }}"
    update_cache: true

- name: Enable and start Docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Copy daemon.json config
  template:
    src: daemon.json.j2
    dest: "/etc/docker/daemon.json"

- name: Restart docker
  ansible.builtin.service:
    name: docker
    state: restarted
